# Generated by Django 5.1 on 2024-08-17 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Promotions', models.CharField(max_length=300)),
                ('intro_title1', models.CharField(blank=True, max_length=400, null=True)),
                ('intro_title2', models.CharField(blank=True, max_length=400, null=True)),
                ('old_price', models.CharField(max_length=14)),
                ('new_price', models.CharField(max_length=14)),
                ('new_price_sub', models.CharField(max_length=14)),
                ('image', models.ImageField(upload_to='banner_image/')),
            ],
            options={
                'verbose_name_plural': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='category_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='category_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.CharField(max_length=13)),
                ('Subject', models.CharField(max_length=450)),
                ('Message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Contact-Infos',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='ProducImage')),
                ('regular_price', models.PositiveIntegerField()),
                ('discount_price', models.PositiveIntegerField(blank=True, null=True)),
                ('descriptions', models.TextField()),
                ('aditional_descriptions', models.TextField()),
                ('stock', models.PositiveIntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
