# Generated by Django 5.1 on 2024-08-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Promotions', models.CharField(max_length=300)),
                ('intro_title1', models.CharField(blank=True, max_length=400, null=True)),
                ('intro_title2', models.CharField(blank=True, max_length=400, null=True)),
                ('old_price', models.CharField(max_length=14)),
                ('new_price', models.CharField(max_length=14)),
                ('new_price_sub', models.CharField(max_length=14)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_image/')),
            ],
            options={
                'verbose_name_plural': 'Banner',
            },
        ),
    ]
